spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled:

jwt:
  issuer: kdm0068@gmail.com
  secret_key: study-springboot
