spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 515672038785-moc9ecctf1b9nrj87d3e125i0d20lrtu.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


jwt:
  issuer: kdm0068@gmail.com
  secret_key: study-springboot
